databases:
  - name: delices-db
    databaseName: delices_db
    user: delices_user
    region: frankfurt

services:
  - type: web
    name: delices-backend
    runtime: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn delices_backend.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: delices-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
